version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/issuetracker/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/run.sh
      time: 180
      runas: ubuntu
