spring:
  profiles:
    active: local
    include: oauth
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.security: debug

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

---

spring:
  config:
    activate:
      on-profile: deploy
  datasource:
    url: jdbc:mysql://AWS_RDS:3306/issuetracker?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    initialization-mode: always
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: AWS_RDS_USER_NAME
    password: AWS_RDS_USER_PASSWORD
