spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.security: debug

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/issuetracker?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    initialization-mode: always
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: test
    password: test

---

spring:
  config:
    activate:
      on-profile: deploy
  datasource:
    url: jdbc:mysql://AWS_RDS:3306/issuetracker?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    initialization-mode: always
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: AWS_RDS_USER_NAME
    password: AWS_RDS_USER_PASSWORD
