name: build-deploy

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  S3_BUCKET_NAME: lynn-issuetracker-deploy
  PROJECT_NAME: issuetracker
  AWS_RDS: ${{ secrets.AWS_RDS }}
  AWS_RDS_USER_NAME: ${{ secrets.AWS_RDS_USER_NAME }}
  AWS_RDS_USER_PASSWORD:  ${{ secrets.AWS_RDS_USER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Change deploy RDS url
        run: sed -i "61s/AWS_RDS/$AWS_RDS/" /home/runner/work/geha-sajang-backend/geha-sajang-backend/src/main/resources/application.yml
        shell: bash

      - name: Change deploy RDS username
        run: sed -i "64s/AWS_RDS_USER_NAME/$AWS_RDS_USER_NAME/" /home/runner/work/geha-sajang-backend/geha-sajang-backend/src/main/resources/application.yml
        shell: bash

      - name: Change deploy RDS password
        run: sed -i "65s/AWS_RDS_USER_PASSWORD/$AWS_RDS_USER_PASSWORD/" /home/runner/work/geha-sajang-backend/geha-sajang-backend/src/main/resources/application.yml
        shell: bash

      - name: Grant excute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Build with gradle
        run: ./gradlew build --stacktrace
        shell: bash

      - name: Notify failure
        run: cat /home/runner/work/issue-tracker-backend/issue-tracker-backend/build/reports/tests/test/index.html
        shell: bash
        if: failure()

      - name: Upload index.html to S3
        run: aws s3 cp --region ap-northeast-2 /home/runner/work/issue-tracker-backend/issue-tracker-backend/build/reports/tests/test/index.html s3://$S3_BUCKET_NAME
        shell: bash
        if: failure()

      - name: Upload reports to S3
        run: aws s3 cp --region ap-northeast-2 /home/runner/work/issue-tracker-backend/issue-tracker-backend/build/reports/tests/test s3://$S3_BUCKET_NAME/error --recursive
        shell: bash
        if: failure()

      - name: Make to zip file
        run: zip -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

      - name: Code Deploy
        run: aws deploy create-deployment --application-name geha-deploy --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name develop --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip
